project:
  type: website

website:
  title: "AzureDataEngineeringStudyNotes"
  sidebar:
    style: "docked"
    search: true
    contents:
      - href: index.qmd
        text: Home
      - section: "Course One"
        contents:
          - href: course1.qmd
            text: Course 1
      - section: "Course Two"
        contents:
          - href: course2.qmd
            text: Course 2
      - section: "Course Three"
        contents:
          - href: course3.qmd
            text: Course 3
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
