---
title: "Data Storage in Microsoft Azure"
---

Syllabus
Week 1
Data storage in Microsoft Azure
In this module, you will learn how using Azure Storage, Azure SQL Database, and Azure Cosmos DB - or a combination of them - for your business scenario is the best way to get the most performant solution. you will also learn how to create an Azure Storage account with the correct options for your business needs.

12 videos, 4 readings, 3 practice quizzes
expandweek 1 material

Graded: Test prep
Week 2
Connect an app to Azure Storage
In this module, you will create a simple application and add configuration, client library references, and code to connect it to Azure Storage.
5 videos, 6 readings, 5 practice quizzes
expandweek 2 material

Graded: Test prep
Week 3
Secure your Azure Storage account
In this module, you will learn how Azure Storage provides multilayered security to protect your data. You will find out how to use access keys, to secure networks, and to use Advanced Threat Protection to proactively monitor your system.
8 videos, 2 practice quizzes
expandweek 3 material

Graded: Test prep
Week 4
Store application data with Azure Blob storage
In this module, you will build an app that stores user files with Azure Blob storage.
4 videos, 5 readings, 2 practice quizzes
expandweek 4 material

Graded: Test prep
Week 5
Practice Exam on Store Data in Microsoft Azure
In this module, you will take a practice exam that covers key skills measured in the Exam DP-203: Data Engineering on Microsoft Azure.
3 videos, 2 readings
expandweek 5 material

Graded: Course practice exam