---
title: "Microsoft Azure for Data Engineering"
---

Syllabus
Week 1
The Evolving world of data and the data engineer
In this module, you will learn how data systems are evolving and how the changes affect data professionals. You will also explore the differences between on-premises and cloud data solutions, and consider sample business cases that apply cloud technologies. you will learn about the responsibilities of a data engineer. You will also find out how they relate to the jobs of other data and AI professionals. You will explore common data engineering practices and a high-level architecting process for a data-engineering project.

More
14 videos, 3 readings, 2 practice quizzes
expandweek 1 material

Graded: Test prep
Week 2
Services on the Microsoft Azure Data Platform
In this module, you will learn about Azure technologies that analyze text and images and relational, nonrelational, or streaming data. You will also see how data engineers can choose the technologies that meet their business needs and scale to meet demand securely. You will take a practice exam that will assess your knowledge of the content of this course and prepare you for the Microsoft Certified: Azure Data Engineer Associate exam.

11 videos, 2 practice quizzes
expandweek 2 material

Graded: Test prep
Week 3
Practice Exam on Store Data in Microsoft Azure
In this module, you will take a practice exam that covers key skills measured in the Exam DP-203: Data Engineering on Microsoft Azure.
2 videos, 2 readings
expandweek 3 material

Graded: Course practice exam