---
title: "AzureDataEngineeringStudyNotes"
---


This resources is a log of useful resources covered while preparing for the Azure Data Engineering Certification.


I want a record of exercises for basic functions performed so I can review in the future when preparing for the exam, and perform work functions when necessary.  The environments change so often that old documentation can be problematic to follow.  I will attempt to make note of important/relevant changes when observed.

# Overview

I am following the overall structure in the Coursera resource: 

Microsoft Azure Data Engineering Associate (DP-203) Professional Certificate
https://www.coursera.org/professional-certificates/microsoft-azure-dp-203-data-engineering


In conjunction with the courses above, I'm following the same material in the Microsoft Learning platform:  https://learn.microsoft.com/en-us/users/michaelbeaulieu/training




Exam DP-900: Microsoft Azure Data Fundamentals
https://learn.microsoft.com/en-us/certifications/azure-data-fundamentals/

Exam DP-203: Microsoft Azure Data Engineer Associate
https://learn.microsoft.com/en-us/certifications/azure-data-engineer/


## Certifications and Learning Paths
https://learn.microsoft.com/en-us/users/collinschedler-0717/collections/40yztymq0o5p3w


### Curriculum Structure

Microsoft Azure for Data Engineering
Course 1
6 hours





Data Storage in Microsoft Azure
Course 2
16 hours





Data Integration with Microsoft Azure Data Factory
Course 3
16 hours


Introduction to Microsoft Azure Synapse Analytics
Course 4
8 hours




Data Warehousing with Microsoft Azure Synapse Analytics
Course 5
14 hours




Data Engineering with MS Azure Synapse Apache Spark Pools
Course 6
7 hours




Operational Analytics with Microsoft Azure Synapse Analytics
Course 7
11 hours




Microsoft Azure Databricks for Data Engineering
Course 8
21 hours




Azure Data Lake Storage Gen2 and Data Streaming Solution
Course 9
9 hours




Prepare for DP-203: Data Engineering on Microsoft Azure Exam
Course 10
5 hours




* Microsoft Azure for Data Engineering
* Data Storage in Microsoft Azure
* Data Integration with Microsoft Azure Data Factory
* Introduction to Microsoft Azure Synapse Analytics
* Data Warehousing with Microsoft Azure Synapse Analytics
* Data Engineering with MS Azure Synapse Apache Spark Pools
* Operational Analytics with Microsoft Azure Synapse Analytics
* Microsoft Azure Databricks for Data Engineering
* Azure Data Lake Storage Gen2 and Data Streaming Solution
* Prepare for DP-203: Data Engineering on Microsoft Azure Exam
